	[BITS 16]
	[ORG 0x7E00]

ENTRYPOINT:
	STI			;Restore interrupts
	MOV SI, TEST_THIS
	CALL DBG_PRINT		;Print about payload
	JMP STARTEXEC

DBG_PRINT:
	PUSHA
	MOV AH, 0x0E
DP_LOOP:
	LODSB
	OR AL, AL	
	JZ DP_END
	INT 0x10
	JMP DP_LOOP
DP_END:
	POPA
	RET

%include "HEADER.h"		;Equates
%include "MATH"
%include "IO"
%include "DATA"			;These are all generated by beta.rb
%include "LANG"
%include "SYS"
%include "test"

STARTEXEC:
	MOV BP, STACK			;Set up forth stack
	MOV word [LAST], FLBL112	;Set LAST pointer to last word

	CALL lbl112			;Call last word (GO)

TEST_THIS: db ">BOOTSTRAP PAYLOAD SUCCESSFUL",13,10,0

ENDKERNEL:			;Used as a reference for HEADER.h
