;String to integer conversion.
;I am so sorry for this disaster

	FPOP SI			;Get string pointer
	
	LODSB			;Get first character
	MOV DI, NUMTABLE
	XCHG SI, DI		;I don't know? It works, though
	MOV BL, AL
NUMLOOP0:
	LODSB
	OR AL, AL
	JZ NOTNUMBER
	CMP AL, BL
	JNZ NUMLOOP0
	MOV AX, [NUMBERSAVE]
	SUB SI, NUMTABLE
	SUB SI, 1
	OR AX, SI
	SHL AX, 4
	MOV [NUMBERSAVE], AX
	XCHG SI, DI		;This happens 4 times, once for each character
	
	LODSB
	MOV DI, NUMTABLE
	XCHG SI, DI
	MOV BL, AL
NUMLOOP1:
	LODSB
	CMP AL, BL
	JNZ NUMLOOP1
	OR AL, AL
	JZ NOTNUMBER
	MOV AX, [NUMBERSAVE]
	SUB SI, NUMTABLE
	SUB SI, 1
	OR AX, SI
	SHL AX, 4
	MOV [NUMBERSAVE], AX
	XCHG SI, DI
	
	LODSB
	MOV DI, NUMTABLE
	XCHG SI, DI
	MOV BL, AL
NUMLOOP2:
	LODSB
	CMP AL, BL
	JNZ NUMLOOP2
	OR AL, AL
	JZ NOTNUMBER
	MOV AX, [NUMBERSAVE]
	SUB SI, NUMTABLE
	SUB SI, 1
	OR AX, SI
	SHL AX, 4
	MOV [NUMBERSAVE], AX
	XCHG SI, DI
	
	LODSB
	MOV DI, NUMTABLE
	XCHG SI, DI
	MOV BL, AL
NUMLOOP3:
	LODSB
	CMP AL, BL
	JNZ NUMLOOP3
	OR AL, AL
	JZ NOTNUMBER
	MOV AX, [NUMBERSAVE]
	SUB SI, NUMTABLE
	SUB SI, 1
	OR AX, SI
	
	FPUSH AX
	
	NEXT
	
NUMBERSAVE: dw 0
NUMTABLE: db "0123456789ABCDEF",0	;Look up table
